# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.3,)" # Require at least 1.3.x

[[mods]]
modId="mcombat"
version="${file.jarVersion}"
displayName="MCombat"
credits="Majavapaja"
authors="Majavapaja"
description='''
MCombat mod description.
'''
[[dependencies.mcombat]]
    modId="forge"
    mandatory=true
    versionRange="[28.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
